services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=/data/urls.db
    volumes:
      - ./backend:/app
      - sqlite-data:/data
    depends_on:
      - db
    networks:
      - url-shortener

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - url-shortener

  db:
    image: keinos/sqlite3:3.49.0
    volumes:
      - sqlite-data:/data
    networks:
      - url-shortener

volumes:
  sqlite-data:

networks:
  url-shortener:
    name: url-shortener-network
    driver: bridge