services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - DB_PATH=./urls.db
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - url-shortener

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - url-shortener

  db:
    image: keinos/sqlite3:3.49.0
    volumes:
      - ./backend/urls.db:/data/urls.db
    networks:
      - url-shortener

networks:
  url-shortener:
    name: url-shortener-network
    driver: bridge